package;

/**
 * ...
 * @author ninjaMuffin
 */
class ChatLogs 
{
	
	public static var specialThanks:Array<Dynamic> =  
	[
		"Special Thanks",
		[
			"In no particular order of importance",
			"Tom Fulp",
			"The pic of Tom in a turtleneck",
			"PhantomArcade",
			"EiGiBeast",
			"Moawling",
			"FuShark",
			"MisterSandmanCT/Cameron Talbot",
			"HIRO NO HIRO",
			"Stuffed Wombat",
			"BrandyBuizel",
			"DigitalFudge",
			"aninvisiblepirate",
			"TheOverGhoul",
			"Tanner Monkman",
			"Brett Procee",
			"Ryan Dugaro",
			"Paol from CFEC",
			"Charles from CFEC",
			"The Youth Zone Staff",
			"Other CFEC Staff",
			"The HaxeFlixel community, specifically the discord",
			"Doki Doki Lit Club",
			"Nina Freeman",
			"Sam Barlow",
			"Kyle Seeley",
			"Ryan Koons",
			"loodumb darray",
			"every single person on Newgrounds.com",
			"specifically the ones who follow me hehe",
			"more specifically the people who upload good stuff",
			"and YOU",
			"the person who cares enough about this game",
			"to see the people that i care about",
			"you are cool"
		]
	];
	
	//SYNTAX -- MONTH, DATE, CHAT
	public static var dates:Array<Dynamic> = 
	[
		//March 10
		[
			3, 10,
			[
				"um hey",
				"hi",
				"youre Dans friend right?",
				"yeah, actually its my real life friend who knows him online",
				"I see, yeah I kinda know Dan from school",
				"we just sorta hang out online though",
				"oh ok",
				"so whats up",
				"nothin much, just really talking to people like you!",
				"haha",
				"what are you up to?",
				"well im supposed to do homework, but here I am instead",
				"haha nice, you in college?",
				"no I'm still in high school",
				"almost done though!",
				"nice"
			]
		],
		//March 23
		[
			3, 23,
			[
				"hey do you mind testing something out for me?",
				"like what?",
				"I'm trying to program a website",
				"and wanna see if I have stuff set up", 
				"and configured correctly",
				"whooaa",
				"just try to head to http://www.vivianconnell.com",
				"i dont think its connected right",
				"shit",
				"so you know about making websites and stuff?",
				"Thats really cool",
				"well i guess i don't know too much about websites",
				"I can barely get this going",
				"how do you even know this stuff?",
				"i'm currently going to college for computer stuff",
				"so naturally there are other people i know who are into it",
				"so i check this stuff out for myself and ask around when I need help",
				"damn youre like one of the coolest people ive talked to",
				"haha yeah right",
				"i mean i cant even get my site going",
				"but i guess i accept your compliment haha",
				"well i dont really know too many people to begin with",
				"i just play video games and stay at home",
				"hey video games are great!",
				"You got a Nintendo 64? or one of those other consoles?",
				"Yep, I just got Ocarania Of Time the other day",
				"also i feel like i spell ocarania wrong every single time haha",
				"haha, that's a good one! Mario 64 has been my thing recently",
				"its so much fun",
				"I still need to pick that one up",
				"Usually I keep up with big game releases",
				"uh oh I gotta pop out",
				"it was cool talking to you again!",
				"yeah same to you 'Vivian' haha!",
				"catch you later",
				"Bye!"
			]
		],		
		//March 27
		[
			3, 27,
			[
				"hey do you mind checking out my site again?",
				"I think i got the hosting configured right this time",
				"yeah",
				"i just see a little under construction animation",
				"nice! I guess it's working now!",
				"haha congratulations I guess!",
				"what do you plan to do with it?",
				"now that it's somewhat working,",
				"i honestly don't know haha",
				"maybe I can post some family photos",
				"for relatives to check out",
				"they live in the north west",
				"so I don't see them too often",
				"hey thats where I live!",
				"Do they live around the Seattle area?",
				"yeah i think so, around that area!",
				"whoa nice.",
				"So I guess that means I'm a few hours behind you then",
				"yep thats how time zones work haha",
				"hey i don't really know anyone out of my own timezone",
				"feels a bit weird",
				"i guess with the internet you'll get used to it",
				"i talk to a few people from different states",
				"yeah i only got internet recently",
				"i had my computer since christmas as well",
				"i was only able to play games on it",
				"and do word processing stuff until recently",
				"now that you have an internet connection",
				"you might wanna check out an MMO i know of",
				"one that i thought was interesting ",
				"its called 'Astonia'",
				"maybe we can both play it sometime",
				"hmm.. yeah I can't say I've heard of it",
				"yeah its pretty obscure",
				"only a small amount of people can be online at once",
				"hmm I'll check it out sometime",
				"yeah",
				"Anyways I gotta get back to studying",
				"yeah same",
				"i've been doing really poorly in my Chemistry class",
				"and if I don't finish, ",
				"I won't graduate and go to college",
				"yikes that sounds pretty intense",
				"good luck with your chemistry stuff",
				"its gonna be close",
				"see ya",
				"bye!"
			]
		],
		//March 30
		[
			3, 30,
			[
				"hey!",
				"whats up",
				"I just got back from school and i finished that chemistry test",
				"oh yeah you mentioned that last time i think",
				"how did you do?",
				"we haven't gotten our marks back yet",
				"i think i did alright though",
				"i atleast learned some stuff on my own about chemistry",
				"well tell me something about science then!",
				"uhh",
				"I really don't know how to explain any of it",
				"something something oxidization",
				"something something balancing reactions",
				"brilliant",
				"nobel prize here i come",
				"these are all mystical words to me",
				"well im sure that you know way more things about computers than i do",
				"and can actually explain them to me",
				"yeah I know a bit",
				"i've been looking into doom engine and stuff like that lately",
				"I love that game!",
				"yeah im mostly just poking around, because there's still a lot that i dont know about",
				"well, you still gotta tell me something about it",
				"since you forced me to haha",
				"haha, alright",
				"how about...",
				"something something bsp trees",
				"dammit",
				"hahaha",
				"now you know how it feels!",
				"we both need to study up some more then",
				"i really hope i passed",
				"my foster mom said she'll give me 100 bucks when I graduate",
				"thats a good amount of used video games",
				"sorry if this is too personal or anything",
				"but what's foster care like?",
				"for the most part its alright",
				"i dont get mistreated or anything",
				"but she's kinda strict about me being on the computer",
				"that kinda sucks",
				"my life is pretty much computers at this point",
				"im so jealous",
				"we'll its not all that glorious",
				"i feel like if i had way more time on the computer id be a programming master",
				"pretty cocky huh haha",
				"well who knows what could have been",
				"maybe i couldve made the best selling PC game by now",
				"how are you gonna distribute it hotshot?",
				"you know thats one of those things that you figure out later down the line",
				"still have a lot of things to learn haha",
				"hey im still pretty much a kid at this point",
				"well youre a high school senior, not too far from being an official adult",
				"you are the millionth person to tell me this, congratulations!",
				"what prize do i win?",
				"ill figure that out later down the line as well",
				"hahahaha",
				"you should plan things like these",
				"imagine if someone else was the millionth person?",
				"that wouldve been awfully embarrasing",
				"having no prize for them",
				"you still owe me that prize though",
				"hey i never actually said ill give you a prize",
				"i just said ill figure that out later haha",
				"well dammit",
				"im actually gonna head to my library to study for a bit",
				"i have a bunch of work to catch up on",
				"no problem",
				"i'll catch up with you later",
				"yeah, maybe i'll start getting into game programming stuff while youre gone",
				"i gotta catch up with your coolness",
				"youre an absolute nerd",
				"see ya",
				"hey ill take that as a compliment",
				"bye"
			]
		],
		//April 3
		[
			4, 3,
			[
				"hey!",
				"oh hey!",
				"you get your tests back after the weekend?",
				"uhhh yeah...",
				"uh oh",
				"how about you take a guess at what grade I got?",
				"hmm",
				"70 percent?",
				"how about try 20 percent",
				"SHIT",
				"yeah",
				"it feels especially bad because i feel like i studied super hard for that test",
				"i even gave my teacher nice compliments on my test haha",
				"who knows, maybe that boosted your mark a bit hahah",
				"i said stuff like 'her hair looked nice today' haha",
				"oh well i guess it wasn't enough to save me",
				"how are tests in college?",
				"we had finals a few months ago and those were rough as hell",
				"i really wanna go to college, but more for the experience",
				"like it could be a change of pace for me and stuff",
				"my foster mom wants me to go, but more so i can meet people an shit",
				"not that its bad to meet people",
				"but i just want to go for my reasons",
				"not hers you know?",
				"have you applied yet?",
				"no, i was gonna do just a year off from school",
				"and really see how i feel i guess",
				"yeah that sounds good",
				"sometimes i really regret going",
				"but i had the chance and i took it",
				"so i dont know",
				"i say if you wanna go, then go",
				"if you dont then dont",
				"but im not a career counsellor so i dont know haha",
				"hey this sounds like decent advice anyways",
				"so thanks!",
				"yeah thought id share my thoughts",
				"sometimes i feel like itll just be same situation different setting",
				"like it wont change me, and ill just be a loser still",
				"well college is for loser nerds anyways",
				"at least the one im at hah",
				"hah, i mean like i wont have many friends",
				"yeah i somewhat had a similar fear",
				"i feel like its likely that overtime",
				"you become more comfortable with your peers if you have similar interests",
				"but hey as ive said before i dont know uh haha",
				"i've got a good while before id have to make those desisions anyhow",
				"all i need to do now is pass this chem class",
				"yeah good luck",
				"im actually gonna head off to bed",
				"ive been staying up way too late recently",
				"and have been unproductive",
				"yeah no problem!",
				"i got homework stuff to catch up on",
				"im super lazy when it comes to homework",
				"i always leave it until the last minute",
				"yeah same!",
				"anyways, have a good night!",
				"you too, catch up on your work kid!",
				"see ya"
			]
		],
		//April 4th
		[
			4, 4,
			[
				"hey",
				"hey!",
				"whats up!",
				"same school stuff",
				"as always",
				"anything new in your life?",
				"spring break is coming up for my school",
				"don't know how im gonna spend my free time though",
				"nice! yeah my break is coming up quick too",
				"you got any plans yourself?",
				"well you know",
				"video games",
				"hah, maybe I'll pick up a gameboy color",
				"and a copy of pokemon to play over the break",
				"Pokemon is so good!",
				"if you get yellow, you get Pikachu to follow behind you",
				"yeah i remember seeing something like that",
				"so its just like the show",
				"yeah",
				"how much you know about pokemon?",
				"not too much",
				"still haven't played the games yet",
				"but i know some misc stuff about it",
				"like you should pick charmander",
				"because it evolves into charzard",
				"come on thats who everyone picks",
				"squirtle is who i pick",
				"i didnt know that water was weak to grass",
				"so i thought that squirtle was the strategic pick",
				"haha, how does that work?",
				"think of it like water helps grass grow",
				"huh",
				"i guess thats kinda clever",
				"yeah most of the types work like that",
				"but if you get yellow, you dont pick between 3",
				"you have to start with pikachu",
				"aw man",
				"pikachu is alright i guess",
				"itd be a cool job to work at Nintendo",
				"mostly to play games before release",
				"yeah nintendo games are fantastic",
				"to this day i still play Super Mario World on my SNES",
				"in general SNES games were a blast",
				"dont even get me started on SNES games",
				"you ever play Chrono Trigger?",
				"ive heard a lot of good things about it",
				"mind giving me a rundown?",
				"yeah sure",
				"basically its a turn based rpg game",
				"where you travel through time",
				"one thing i like about it",
				"is that you can pretty much fight the final boss whenever",
				"but he'll most likely destroy you if you're underpowered",
				"haha, thats cool",
				"how far have you gotten?",
				"not that i'd even know hah",
				"i think im almost done",
				"im at this spooky dark castle",
				"the game is so good",
				"yeah with college stuff i dont play too many rpgs anymore",
				"last one i played was that Mario RPG",
				"yeah that was a good one",
				"i think a new Mario RPG style game is coming to the N64",
				"i don't know too much about it though",
				"hmm hopefully i have time for that once its out",
				"Nintendo games are so good",
				"hey i gotta go take care of some stuff",
				"alright bye!",
				"bye"
			]
		],
		//April 7th
		[	
			4, 7,
			[
				"hey you live in the Seattle area right?",
				"yeah why?",
				"im heading to my cousins for spring break",
				"you wanna meet up for a day or something",
				"woah",
				"i mean sure",
				"your cousins would be cool with it?",
				"yeah i told them about you, you can tag along with us",
				"my cousins are around my age",
				"i get kinda anxious around others",
				"dont worry they're real cool",
				"like how you think i am haha",
				"dammit",
				"yeah alright",
				"my foster mom would probably like it since itll get me outta the house",
				"nice! I'm looking forward to it!",
				"i'll be flying over on monday and we can meetup Tuesday or wednesday?",
				"we can message back and fourth on Tuesday",
				"to schedule thigns, my cousins have a computer i can use",
				"sounds like a plan!",
				"right now im busy with some stuff so i'll get back to you then",
				"alright, see ya",
				"bye"
			]
		],
		//April 11th
		[
			4, 11,
			[
				"hey im at my cousins right now",
				"you wanna meet at McDonalds tomorrow at 12?",
				"yeah, i dont live too far from it",
				"im so excited",
				"same",
				"so the plan is pretty much do whatever around the city",
				"i really wanna sight see and stuff",
				"i havent been here for a while",
				"what are you up to today?",
				"just catching up with my cousins",
				"cool"
			]
		],
		//April 17th
		[
			4, 17,
			[
				"hey Nina! It was cool to hang out with you when I was in Seattle",
				"Nina?"
			]
		],
		//April 20th
		[
			4, 20,
			[
				"Hello?",
				"Nina!",
				"Did you get my last message?",
				"yes, it was nice to meet with you too Vivian",
				"sorry I can't talk right now",
				"oh thats alright",
				"we can talk whenever you feel like",
				"just thought id let you know my cousins thought you were cool haha"
			]
		],
		//April 21st
		[
			4, 21,
			[
				"This is officer Cheng from the Seattle Police Department",
				"the fuck",
				"i'd like to ask you questions about Nina Faye",
				"umm is this real?",
				"yes",
				"judging from previous messages",
				"You were one of the last people Nina saw before she went missing",
				"on the night of April 16th",
				"no fucking way",
				"shit",
				"do you mind if i can ask some questions?",
				"hoooly shit",
				"sorry",
				"its alright",
				"so yeah go ahead and ask me questions",
				"ok",
				"first question",
				"how did you and Nina meet?",
				"well, we were both in the same IRC chat with some friends",
				"i think we had mutual friends",
				"ok",
				"how long do you think you and Nina have been in contact?",
				"i think we met in that IRC chat late Feb to early March",
				"but i think we really started knowing each other in March",
				"question three",
				"how much do you know about Nina?",
				"i know she's just finishing high school",
				"she's living with a foster parent",
				"she's into video games?",
				"not sure how relavent that bit is",
				"anything in particular you'd need to know?",
				"how do you think she was emotionally",
				"i dont really know",
				"she seemed really cheery and happy when i met her",
				"and online it was more or less the same",
				"do you know anyone in her personal life?",
				"not really",
				"ive heard about her foster mom",
				"but i dont really know much about her",
				"now",
				"if you dont mind",
				"i'll be ask questions about you",
				"are you comfortable with that?",
				"sure",
				"is this going to help the case?",
				"hopefully",
				"anyways, please tell me your full name",
				"Vivian Connell",
				"Where do you live?",
				"Boston",
				"Where do you work?",
				"I'm a student at MIT",
				"alright",
				"for further questioning",
				"I'll be sure to get the Boston Police to contact you",
				"and have them forward answers to me",
				"alright",
				"hey, was there any reason we had to do this online?",
				"would it have been easier for me to head to the station?",
				"hello?"
			]
		],
		//April 25th
		[
			4, 25,
			[
				"FUCKFUCKFUCKFUCK",
				"NINA?!",
				"Who is this?",
				"Whoever this is please tell me whats going on?",
				"is nina ok?",
				"jesus christ",
				"please"
			]
		],
		//April 29th
		[
			4, 29,
			[
				"hey long time no see",
				"what the hell",
				"?",
				"nina what the fuck happened",
				"sorry?",
				"are you kidding me",
				"are you seriously kidding me",
				"Viv what did I do?",
				"are you 100 percent serious with me?",
				"i have no idea what you're talking about",
				"and it's kinda freaking me out",
				"how are you talking to me?",
				"oh yeah,",
				"my computer broke a week or two ago",
				"so i haven't been able to talk online",
				"im at my library",
				"Nina, if this is really you",
				"check our previous messages",
				"holy shit",
				"what the hell is this?",
				"did you run away or something?",
				"NO!",
				"I'm terrified right now",
				"holy fuck",
				"Nina",
				"I don't even know what to say",
				"who ever this is",
				"they has access to your account",
				"they know where I live",
				"they know how to find both of us",
				"god",
				"some creepy stuff is happening",
				"they know where you are right now",
				"they're probably reading these messages right now",
				"you need to find someplace safe and call the cops",
				"dont message me back",
				"we need to stop talking",
				"i don't know if we'll ever talk again",
				"this is goodbye",
				"bye vivian"
			]
		]
	];
	
}